version: '3'
services:
  frontend:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./server
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
